import dotenv from "dotenv";

dotenv.config();

const { 
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  DISCORD_CHANNEL_ANNONCE,
  DISCORD_CHANNEL_BOT,
  DISCORD_GUILD_ID,
  TWITCH_CLIENT_ID,
  TWITCH_CLIENT_SECRET,
  TWITCH_WEBHOOK_SECRET,
  TWITCH_PORT,
  TWITCH_CALLBACK_URL,
  TWITCH_CHANNEL_NAME,
  TWITCH_BOT_NAME,
  TWITCH_WS_OAUTH_TOKEN,
  DISCORD_INVITE_URL,
  YOUTUBE_URL,
  GITHUB_URL,
  APP_ENV,
  CERT_PATH
} = process.env;

if (!DISCORD_TOKEN || !DISCORD_CLIENT_ID) {
  throw new Error("Missing environment variables");
}

export const config = {
  ROLES: {
    nouveau_challenger: 1308056467567411260,
    hero_arene: 1308056993428406315,
    forgeron: 1308057542156619898,
    spectateur_elite: 1308058014179131443,
  },
  APP_ENV: APP_ENV ?? 'dev',
  CERT_PATH: CERT_PATH ?? '',
  DISCORD_TOKEN,
  DISCORD_BOT_ID: '1310622513872638154',
  DISCORD_CLIENT_ID,
  DISCORD_CHANNEL_ANNONCE: DISCORD_CHANNEL_ANNONCE ?? "",
  DISCORD_CHANNEL_BOT: DISCORD_CHANNEL_BOT ?? "",
  DISCORD_GUILD_ID,
  TWITCH_CLIENT_ID,
  TWITCH_CLIENT_SECRET,
  TWITCH_WEBHOOK_SECRET: TWITCH_WEBHOOK_SECRET ?? "",
  TWITCH_PORT,
  TWITCH_CALLBACK_URL,
  TWITCH_CHANNEL_NAME: TWITCH_CHANNEL_NAME ?? "",
  TWITCH_EVENTSUB_WEBSOCKET_URL: 'wss://eventsub.wss.twitch.tv/ws',
  TWITCH_WS_OAUTH_TOKEN: TWITCH_WS_OAUTH_TOKEN || undefined,
  TWITCH_BOT_NAME: TWITCH_BOT_NAME ?? TWITCH_CHANNEL_NAME,
  TWITCH_BOT_USER_ID: '',
  TWITCH_CHAT_CHANNEL_USER_ID: '',
  TWITCH_WS_SESSION_ID: '',
  DISCORD_INVITE_URL: DISCORD_INVITE_URL,
  YOUTUBE_URL: YOUTUBE_URL,
  GITHUB_URL: GITHUB_URL,
  DATABASE_PATH: './bot.db'
};
